# Generated by Django 5.0.7 on 2024-07-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0002_available_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='country',
            field=models.CharField(default='USA', max_length=100),
        ),
    ]
