# Generated by Django 5.0.7 on 2024-07-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0003_available_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='available',
            name='adopted_by',
            field=models.CharField(default='', max_length=300),
        ),
    ]
