# Generated by Django 5.0.7 on 2024-07-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0006_donations_delete_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donations',
            old_name='user_type',
            new_name='currency',
        ),
        migrations.AddField(
            model_name='donations',
            name='name',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
