# Generated by Django 5.0.7 on 2024-07-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0007_rename_user_type_donations_currency_donations_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donations',
        ),
    ]
